version: "3.1"

services:
  mysqldb:
    image: mysql:5.7.43
    hostname: mysqldb
    # command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - "3307:3306" # turn on for testing
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_root_password
      MYSQL_DATABASE: buy_online_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  product_updater:
    build: ./product_updater
    container_name: product_updater
    restart: on-failure
    volumes:
      - ./data:/usr/src/app/data
    command: ["sh", "-c", "python wait_for_mysql.py && python product_updater.py 2>&1"]
    environment:
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: buy_online_db
    depends_on:
      - mysqldb
      - consumer_1
      - consumer_2
      - consumer_3
      - consumer_4
      - consumer_5

  producer:
    build: ./producer
    container_name: producer
    restart: on-failure
    command:
      - sh
      - -c
      - "python wait_for_mysql.py && python producer.py 2>&1"
    environment:
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: buy_online_db
    volumes:
      - ./time_track:/usr/src/app/time_track
    depends_on:
      - mysqldb
      - consumer_1
      - consumer_2
      - consumer_3
      - consumer_4
      - consumer_5

  consumer_1:
    build: ./consumer
    restart: always
    command:
      - python
      - consumer.py
    environment:
      CONSUMER_NAME: Consumer_1
    volumes:
      - ./consumer_logs/consumer_1:/usr/src/app/consumer_log

  consumer_2:
    build: ./consumer
    restart: always
    command:
      - python
      - consumer.py
    environment:
      CONSUMER_NAME: Consumer_2
    volumes:
      - ./consumer_logs/consumer_2:/usr/src/app/consumer_log

  consumer_3:
    build: ./consumer
    restart: always
    command:
      - python
      - consumer.py
    environment:
      CONSUMER_NAME: Consumer_3
    volumes:
      - ./consumer_logs/consumer_3:/usr/src/app/consumer_log

  consumer_4:
    build: ./consumer
    restart: always
    command:
      - python
      - consumer.py
    environment:
      CONSUMER_NAME: Consumer_4
    volumes:
      - ./consumer_logs/consumer_4:/usr/src/app/consumer_log

  consumer_5:
    build: ./consumer
    restart: always
    command:
      - python
      - consumer.py
    environment:
      CONSUMER_NAME: Consumer_5
    volumes:
      - ./consumer_logs/consumer_5:/usr/src/app/consumer_log

