version: '3.1'

services:
  mysqldb:
    image: mysql
    hostname: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"  # for testing
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_root_password
      MYSQL_DATABASE: buy_online_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  product_updater:
    build: ./product_updater
    container_name: product_updater
    restart: on-failure
    # volumes:
      # - ./data:/usr/src/app/data
    command: ["python", "product_updater.py"]
    environment:
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: buy_online_db
    depends_on:
      - mysqldb

  producer:
    build: ./producer
    container_name: producer
    restart: on-failure
    command:
      - python
      - producer.py
    environment:
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: buy_online_db
    volumes:
      - ./time_track:/usr/src/app/time_track
    depends_on:
      - mysqldb


